export const NAV_ROUTE: Array<any> = [
  {
    id: 2,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Dashboard',
    routeLink: '/dashboard',
    routeModule: [1],
    routeTitle: 'Dashboard',
    routeIcon: 'bw_statistics',
    divider: '0',
    hidden: false,
    submenu: [],
  },

  {
    id: 3,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Map',
    routeLink: '/map',
    routeModule: [1],
    routeTitle: 'Map',
    routeIcon: 'pin_drop',
    divider: '0',
    hidden: false,
    submenu: [],
  },
  {
    id: 6,
    idModule: 0,
    readWrite: 0,
    routeDescription: 'Paramétrage',
    routeLink: '',
    routeModule: 'subMenu',
    routeTitle: 'Paramétrage',
    routeIcon: 'build',
    divider: '1',
    hidden: false,
    submenu: [
      {
        id: 7,
        idModule: 0,
        readWrite: 1,
        routeDescription: 'Types et Catégories',
        routeLink: '/type-category',
        routeModule: [0],
        routeTitle: 'Types et Catégories',
        routeIcon: '',
        divider: '0',
        submenu: [],
      },
      {
        id: 10,
        idModule: 0,
        readWrite: 0,
        routeDescription: 'Compte',
        routeLink: '/configAccount',
        routeModule: [0],
        routeTitle: 'Compte',
        routeIcon: '',
        divider: '0',
        submenu: [],
      },
    ],
  },
];
